/pose_evaluator_node:
  ros__parameters:
    camera_filter_type: simple
    object_filter_type: simple
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    sigma_a: 0.00001
    sigma_alpha: 0.00001
    sigma_px: 0.5

    use_plane_motion_constraints: true

    plane_sigma_pz: 0.001
    plane_sigma_vz: 0.001
    plane_sigma_nx: 0.001
    plane_sigma_ny: 0.001
    plane_sigma_wx: 0.001
    plane_sigma_wy: 0.001

    start_type_description_service: true
    use_sim_time: false

